include:
  - ./backend/docker-compose.yml

services:
  frontend:
    build: ./frontend
    container_name: webrepl-frontend
    ports:
      - "${FRONTEND_PORT:-8080}:80"
    environment:
      - FRONTEND_PORT=${FRONTEND_PORT:-8080}
      - CORS_ORIGINS=${CORS_ORIGINS:-http://localhost:8080}
    depends_on:
      - backend-python
      - backend-javascript
      - backend-ruby
      - backend-php
      - backend-kotlin
      - backend-haskell
    restart: unless-stopped
    networks:
      - webrepl-network

networks:
  webrepl-network:
    driver: bridge